services:
  redis:
    container_name: trailtag-redis
    image: redis:7-alpine
    command: ["sh", "-c", 'redis-server --requirepass "%@z%dVBRS2f8io"']
    # ports:
    #   - "6380:6379"
    restart: always
    networks:
      - trailtag-network

  backend:
    container_name: trailtag-backend
    image: sacahan/trailtag-backend:latest
    command: ["sh", "-c", "uvicorn src.api.main:app --host 0.0.0.0 --port 8010"]
    ports:
      - "8010:8010"
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - REDIS_PASSWORD=%@z%dVBRS2f8io
      - REDIS_EXPIRY_DAYS=7
    depends_on:
      - redis
    restart: always
    networks:
      - trailtag-network

networks:
  trailtag-network:
    driver: bridge
