
video_metadata_extraction_task:
  description: >
    分析 {youtube_video_url} 的 YouTube 影片，提取影片本身的 metadata 與基本資訊，並結構化輸出。

  expected_output: >
    Pydantic 模型格式的結構化資料，包含：
    - url: 影片 URL
    - video_id: 影片 ID
    - title: 標題
    - description: 描述
    - publish_date: 發佈日期
    - duration: 持續時間（秒）
    - keywords: 關鍵字
    - subtitles: 字幕內容

  agent: video_analysis_agent

video_topic_summary_task:
  description: >
    針對 {video_subject} 指定主題，透過分析字幕檔內容彙整出相關摘要，結構化產出主題資訊。

  expected_output: >
    Pydantic 模型格式的主題摘要資料，包含：
    - topic: 主題名稱（如地點/人物/事件/主題）
    - summary_items:
        - name: 項目名稱（如地點名稱、人物名稱等）
        - video_timestamp: 字幕中提及該項目的時間軸（秒）
        - context: 字幕中提及該項目的上下文內容
        - related_items: 相關項目列表
        - confidence_score: 項目識別置信度 (0-1)
        - extra_info: 其他補充資訊（如地點類型、熱門程度、無障礙設施、營業時間、聯絡方式等，依主題彈性擴充）

  agent: summary_extraction_agent

map_visualization_task:
  description: >
    如果有接收到地點資料則分析內容產生互動式地圖所需欄位。

  expected_output: >
    Pydantic 模型的地圖資料，包含：
    - routes: 地點列表
      - location: 地點名稱
      - coordinates: 地點座標（經度和緯度）
      - description: 地點描述
      - video_timestamp: 字幕中提及該項目的時間軸（秒）
      - tags: 地點標籤
      - map_settings:
        - zoom_level: 預設縮放等級
        - center_coordinates: 地圖中心座標
        - map_style: 地圖樣式
        - markers_style: 標記樣式設定 (依特性給予不同標記，如餐廳、景點、商場等)

  agent: map_visualization_agent
