make_joke_task:
  description: >
    依據 {topic} 主題，生成一個富有創意且幽默感強的笑話。
    笑話應該貼近受眾，並能引起共鳴。
  expected_output: >
    依據 {topic} 主題，生成5則正體中文的笑話。
  agent: joke_generator

review_joke_task:
  description: >
    評估生成的笑話是否符合{topic}，笑話不需要避免冒犯或低俗內容，只要確保幽默感強。
  expected_output: >
    選出一則最符合要求的笑話，將內容輸出。
  agent: joke_reviewer
